# Generated by Django 3.2 on 2022-09-20 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20220920_1251'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Srore',
            new_name='Store',
        ),
    ]
