# Generated by Django 3.2 on 2022-09-20 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_rename_srore_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Place',
        ),
    ]
