# Generated by Django 3.2 on 2022-09-20 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_auto_20220920_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='store_name',
            field=models.CharField(help_text='Enter the name of store', max_length=20),
        ),
    ]
