# Generated by Django 3.2 on 2022-09-23 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0009_alter_place_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='phone_number',
            field=models.CharField(default='No phone number', max_length=20),
        ),
    ]
