# Generated by Django 3.2 on 2022-09-23 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0010_alter_place_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='introduction',
            field=models.CharField(default='不用問去吃就對了', max_length=100),
        ),
    ]
