# Generated by Django 3.2 on 2022-09-23 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0011_place_introduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='place',
            field=models.ForeignKey(help_text='The place that this photo come from.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='food.place'),
        ),
    ]
