# Generated by Django 3.2 on 2022-09-28 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0012_photo_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Data_Management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.place')),
                ('referrer', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relationship', to='food.place')),
                ('tags', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.tag')),
            ],
        ),
        migrations.AddField(
            model_name='place',
            name='tags',
            field=models.ManyToManyField(through='food.Data_Management', to='food.Tag'),
        ),
    ]
