# Generated by Django 3.2 on 2022-09-28 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0014_remove_data_management_referrer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameModel(
            old_name='Data_Management',
            new_name='Tag_Management',
        ),
        migrations.CreateModel(
            name='Device_Management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devices', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.device')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.place')),
            ],
        ),
        migrations.AddField(
            model_name='place',
            name='devices',
            field=models.ManyToManyField(through='food.Device_Management', to='food.Device'),
        ),
    ]
