# Generated by Django 3.2 on 2022-09-29 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0016_auto_20220929_0741'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Device_Management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devices', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.device')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.place')),
            ],
        ),
    ]
