# Generated by Django 3.2 on 2022-10-02 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0017_device_device_management'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='devices',
            field=models.ManyToManyField(to='food.Device'),
        ),
    ]
