# Generated by Django 3.2 on 2022-10-02 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0018_place_devices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='tags',
        ),
        migrations.AddField(
            model_name='place',
            name='tag',
            field=models.ManyToManyField(to='food.Tag'),
        ),
        migrations.DeleteModel(
            name='Tag_Management',
        ),
    ]
