# Generated by Django 3.2 on 2022-10-02 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0019_auto_20221002_0352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='devices',
            field=models.ManyToManyField(null=True, to='food.Device'),
        ),
        migrations.AlterField(
            model_name='place',
            name='tag',
            field=models.ManyToManyField(null=True, to='food.Tag'),
        ),
    ]
