# Generated by Django 3.2 on 2022-10-09 07:07

from django.db import migrations, models
import food.models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0021_auto_20221002_0359'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='value',
            field=models.CharField(default='None', max_length=30),
        ),
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=models.ImageField(upload_to='photos', validators=[food.models.validate_file_size]),
        ),
    ]
