# Generated by Django 3.2 on 2022-10-12 08:24

from django.db import migrations
import django_resized.forms
import food.models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0022_auto_20221009_0707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='PNG', keep_meta=True, quality=-1, scale=None, size=[400, 400], upload_to='photos', validators=[food.models.validate_file_size]),
        ),
    ]
