# Generated by Django 3.2 on 2022-10-13 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0023_alter_photo_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='style',
        ),
        migrations.AddField(
            model_name='tag',
            name='group',
            field=models.CharField(choices=[('V', 'vegen_style'), ('C', 'category'), ('F', 'food_style')], default='F', max_length=30),
        ),
    ]
