# Generated by Django 3.2 on 2022-10-14 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0024_auto_20221013_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='group',
            field=models.CharField(choices=[('V', 'vegan_style'), ('C', 'category'), ('F', 'food_style')], default='F', max_length=30),
        ),
    ]
