# Generated by Django 3.2 on 2022-10-26 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0026_alter_tag_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='pub_date',
            field=models.DateField(auto_now=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='value',
            field=models.CharField(default='None', max_length=30),
        ),
    ]
