# Generated by Django 3.2 on 2022-10-26 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0029_auto_20221026_0502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='pub_date',
        ),
    ]
